version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wordflow_db
      - POSTGRES_USER=wordflow_user
      - POSTGRES_PASSWORD=wordflow_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  media_volume:
