# Generated by Django 5.2.6 on 2025-09-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordflow', '0015_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
