# Generated by Django 5.2.6 on 2025-09-15 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordflow', '0023_category_post_category_text_alter_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_text',
        ),
        migrations.AddField(
            model_name='post',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wordflow.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=3, max_length=600),
            preserve_default=False,
        ),
    ]
