# Generated by Django 5.2.6 on 2025-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordflow', '0026_remove_post_tags_alter_post_content_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='16 September 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='16 September 2025', max_length=100),
        ),
    ]
