# Generated by Django 5.2.6 on 2025-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordflow', '0028_globaleditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/posts'),
        ),
    ]
